[build]
  base = "/"          
  publish = "apps/mmm-noodle-soup/public"
  command = "turbo run build --filter=mmm-noodle-soup..."

[build.environment]
  NODE_VERSION = "22.14.0"

[functions]
  directory = "apps/mmm-noodle-soup/netlify/functions"
